// articles.js
// Expose a small articles dataset and rendering helpers so pages (like index.html)
// can pull content dynamically.
const articles = [
    {
        title: "Outlining",
        summary: `<p><em><b>By Megan Kissling</b></em></p>
        Outlining. Preparation…the first big hurdle to overcome when writing.
        <br>From just a general sketch of your entire novel, beginning to end, to the tiny little details that shape your main character (mc), outlining is a big task.
        <br>Some tend to outline everything, others only outline enough to give them an idea of what they’re doing, and some don’t outline at all. Each of these different types have been assigned their own name in the writer's world. A plotter can not seem to get anything words onto paper without first planning out every piece of their story, world and characters. A pantser doesn’t do any outlining at all and just writes whatever comes to them, when it comes to them. And then there's the plottzer, the happy medium, the one who makes a general outline to help guide them along their journey, but who doesn’t sweat when the 37 hens that the sidekick has aren’t all named.
        <br>The more I’ve engaged with other authors the more I’ve realized that a good many of us are plottzers. We like to have a map to help us along and we like to just write when inspiration strikes. 
        <br>The only problem after discovering that is…well…what is an outline? What does it look like? Where can I get one?
        <br>An outline could be anything from a paragraph per chapter doc, explaining what you want to happen in each chapter in one paragraph, it could be a list of quirks you want your character to have, it could even be a map of your world with lists of each countries success’s, resources and any worldbuilding you have.
        <br>So, here’s several different outlines, ones that I use in my writing, that you can use to help you create your own personalized map!
        <br><br><a href="https://docs.google.com/document/d/1WoZsyFmRgYV8UgBEgi8HM6npU_6fB6RbLW2UxSSbgwo/edit?tab=t.0">Storyworld</a>
        <br><br><a href="https://docs.google.com/document/d/1WoZsyFmRgYV8UgBEgi8HM6npU_6fB6RbLW2UxSSbgwo/edit?tab=t.odbktgvo73n7">Mind Maps</a>
        <br><br><a href="https://docs.google.com/document/d/1WoZsyFmRgYV8UgBEgi8HM6npU_6fB6RbLW2UxSSbgwo/edit?tab=t.qzakkqr3c5kc">Characters</a>
        <br><br><a href="https://docs.google.com/document/d/1WoZsyFmRgYV8UgBEgi8HM6npU_6fB6RbLW2UxSSbgwo/edit?tab=t.y7o798u9858n">Chapter by Chapter outline</a>
        <br><br><a href="https://docs.google.com/document/d/1WoZsyFmRgYV8UgBEgi8HM6npU_6fB6RbLW2UxSSbgwo/edit?tab=t.46d6sf6fc914">General Sketch</a>`
    },
    {
        title: "Countering the Idea of Relativism",
        summary: `<p><em><b>By Carson Bullington</b></em></p>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Introduction<br>
        <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In recent years, a seductive ideology, named relativism, has captivated the world. This idea is that all people have their own personal truths–Truths that are only true to the person in question, and that it does not apply to others. These truths are subjective, unaccountable, and often contradictory. It promotes lawlessness and sin, not only promoting it, but celebrating it. 
        <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This idea is arising in pop culture and especially the entertainment industry. Disney especially has used this ideology to pull in youth, creating tempting slogans like “follow your heart” and “be yourself”. Though this idea is becoming popular, and fast, this myth is illogical and an immoral lie. This is a foul tale told by the Devil that has plagued Man from the beginning of time.
        <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. The Origin
        <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Satan himself crafted this lie, when in the beginning he spoke to Eve, asking the question, “did God really say…” Though the basis has changed, the basic idea still remains, that we are bound by “false” truths that we must break out of, yet the opposite is true. The Greek philosopher Protagoras came to the conclusion that “Man is the measure of all things” which started the idea that truth and reality are relative to the individual. 
        <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C.S. Lewis warned that abandoning shared moral frameworks leads to a fragmented society, where people are “adrift” in subjective desires without a grounding in reality and in modern society this is becoming more and more of a problem. The American Constitution introduced the ideas of “liberty and justice for all” through this awe inspiring section.
        <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;“Congress shall make no law… abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble…” 
        <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Though the beliefs of liberty, justice, and free speech are biblical, and it does not directly promote the idea of relativism, it does allow the building of foundation of a culture that prizes freedom to believe in anything an individual wishes, instead of one that focuses on the search for the truth. The freedom of belief has been twisted and used for evil by modern society. More recently the social movement calling themselves the “Pride” or “LGBT+” movement have also affected the societal beliefs among youth, encouraging them to believe in their own “truths”. In the end this merely so called “philosophical awakening” is only a broken people’s rebellion against the one true God of the Bible, poisoning the waters so to say.
        <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. Problematic Logic
        Though this idea has become quite popular it has significant logic problems, both scientific and moral. On the scientific side we can easily break down relativism. Let’s say you were to jump off a cliff, you can believe all you want that you will fly or land softly on your feet, yet you will plummet to your death, and the same can be said for the idea of relativism. You can believe in your “truths” all you want, yet at the judgement day they will crumble.
        Just like the laws of physics, the moral laws, built by an omniscient Creator, are carved into stone, undeniable and unchanging. Man says that we are not bound by an ultimate truth, yet we still acknowledge good, evil, love, and hatred, are these not truths? No man can say truthfully that murder is just and good. 
        <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Many psychologists and scientists have claimed that these moral laws are merely ideas oppressed upon us by our ancestors, yet scientists have discovered that certain parts of our brain, mainly the medial prefrontal cortex, temporoparietal junction, and the amygdala, help make moral judgements which attribute to the process of conscious.
        Like the idea of ancestral impression, philosophers and scientists have also reasoned that the cause of our mold of moral ideologies is attributed to people in power who do often impress their ideologies upon people in their control, as the famous quote attributed to Sir Francis Bacon says “knowledge is power”. The quote itself is very wise, for many men have used knowledge as a way to control their people, but many rulers have attempted to override the moral laws these scientists claim to have been manifested by man, yet still they persist in modern society. These laws have been acknowledged by the whole world, which is why people such as the dictators, Hitler and Stalin of Germany and Russia have been considered some of the vilest men in history.
        <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In conclusion this ideology’s basis is completely illogical, for if everyone has different truths isn’t conflict inevitable? Tolerance is impossible, and as a Christian I am ready to be hated by this world for my beliefs. Are you?
        <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4. What Scripture Says About Truth
        “And no wonder, for Satan himself masquerades as an angel of light.” 2 Corinthians 11:1. The Bible says Satan, in the verse John 8:44, “You belong to your father, the devil… When he lies, he speaks his native language, for he is a liar and the father of lies.” The Devil portrays himself as an angel of light, offering sinful delicacies wrapped in beautiful charm. Everything he tells us is merely lies, as Lucifer (the Devil) is called the father of lies, all that he speaks is false and twisted truths. 
        What a great contrast the truth that has been given to us by the holy Creator is against the darkness of the Devil who hates! Jesus, the incarnate Messiah, said this about what is truth, Jesus said, “I am the way, the truth, and the life.” Jesus Himself is the Truth, the Word, the Son of God, He defines, in His perfect human life, the truths given to us by God. Overall God has orchestrated the truths of this world, and He has done so magnificently! In Matthew 22:16, the teachers of the law, who hated Jesus, acknowledged the fact that Jesus spoke perfect and unbiased truth when they said this, “Teacher, we know that You are truthful and teach the way of God in truth…” Jesus spoke with such power, wisdom, and authority, that even the people that wished to kill Him recognized His divine and heavenly knowledge. Jesus spoke against every evil thing that we can clearly see to be so. 
        Society claims that we have been bound by the truths that have been impressed upon us by “intolerant” and “hateful” people, yet the Scriptures speak of freedom through the truth of the gospel, as Jesus said, “You will know the truth, and the truth will set you free” (John 8:32) The lies of our culture tell us that the Truth restricts us, yet the opposite is true! When we come to the truth of the gospel, we will be set free from the slavery of sin! My heart yearns for every man, woman, and child to be freed from the Devil’s binds, yet he continues to pull many from the Truth, and few will enter the Kingdom
        <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;“Enter through the narrow gate. For wide is the gate and broad is the road that leads to destruction, and many enter through it. But small is the gate and narrow the road that leads to life, and only a few find it.” (Matthew 7:13–14)
        God has invited you to His wedding banquet. Will you come? “For many are invited, but few are chosen.” (Matthew 22:14)`
    },
    {
            title: "Writing Process (Inspiration/Idea)",
            summary: `<p><em><b>By Megan Kissling</b></em></p>
            <h5>The ones who are crazy enough to think they can change the world are the ones who do.
            <br>- Steve Jobs -</h5><br>
            <p>In my last post we discussed each piece of the writing process briefly. Just touching on the basics.  Today we’ll be taking the first step, Inspiration/Idea and diving deep into what it means. How to get it. How to cultivate it. How to use it to the best of your ability. So let's get started!<br>
            <br>How to get it: Well, this one should be fairly obvious, and if it's not, a quick read of my last post should explain it and if still not, then…I don’t know what you’re gonna do. But either way, inspiration doesn't have to be intricate book ready quality. All it takes is a few words from a song, a picture, a scene in a movie, or even just mindlessly thinking about how hot it is outside and how much you really don’t want to haul 4 five gallon buckets of water for your cow —- don’t even ask 🥵 —- when inspiration can strike. And then all of a sudden you become energized, your brain begins working double time and it's all you can do to wait until you have a piece of paper to scribble your ideas on.<br><br>Now, getting inspiration is the easy part…keeping inspiration…that's a lot harder. I’ve heard lots of ideas on how to keep inspiration, constantly think about it, add trillions of elements to try to make it more exciting, just sit and write and write and write so you don’t lose it and forget to engage in life… yeah, those don’t work too well, for a little bit they might be fine, but at some point you’re gonna get burnt out, and then you can’t even think, much less write it all out. There is a simple solution, many of you have probably heard it before, some of you may have not, but the whole problem is solved with one word. Consistency. Yep. That's it. All you gotta do is consistently write, plan, think, imagine, brainstorm, every day, and you won’t lose that inspiration, that idea that was sparked inside of you. Of course, there will be days when it certainly feels like you’ve lost it, when all you can manage is to write a two word sentence and you have no incentive whatsoever to keep going, but oftentimes, that's just a laziness in the author themselves when they don’t want to write a “boring part” to their story, but it has to be in there, they think the solution is to just not write and everything will be better, five months later they might finally put some effort into twisting the part into something not so boring, but by then all that fresh perspective is long gone. This is a mistake. A  big mistake. This is what makes many wannabe authors give up. And it's only the first step! Consistency is key to solving this problem, even if you just write for five minutes a day, or put a sentence onto paper, that will keep that spark alive. 
            Alright, I kinda got off into the weeds, we’re talking about ideas and the inspiration for those ideas, not how to keep inspiration. Now, some people struggle with finding ideas, or finding the “perfect” idea, they try and try and try to just “let it find them” but it never comes. That's not because you’re not meant to be an author, no, there's a good chance that God just has a better idea, more worthy of your amazing authoryness, (yes! This most certainly is a word!) than to have you write a random, cliche book about a princess being carried off by a knight in shining armor. Either way here are a couple prompts/things that spark ideas
            <ul>
            <li>Listen to a song and focus intently on the lyrics, what story they’re trying to tell you, what theme, sadness, happiness, faith etc. are they trying to convey? (For instance, just the other day we were in the car each member of my family picking different songs and the one my dad picked, ‘Watch the lamb’ piqued my interest. I started to pay attention to the lyrics and halfway through the song, right when the words “arrogant and loud” were uttered, another idea to add to my collection sprouted. One to be based on the lives of the men who were crucified along with Jesus.)</li>
            <li>Quotes! Take a quote, it can be your favorite quote, a Bible verse, something a family member said, or even just a line that for some random reason you like, and start picturing it as the outline for an entire story. This works really well and takes almost no effort. A line I like to make my “motto” “We’ve already done stupid, we might as well add crazy,” opens the mind to hundreds upon hundreds of scenarios. Someone about to attempt to jump from a plane several hundred feet in the air with a half broken parachute but determination to save their family and trying to stay wonderfully optimistic about the whole thing…. like I said, the possibilities are endless.</li>
            <li>Book titles. These are another great way to get some inspo. Literally, I was just at a bookstore the other day and scanning the titles sent my mind in thousands of different directions, although some of those titles were… strange.</li>
            </ul>
            <br>Now, how many of you at least have an inkling of inspiration? Hopefully it’s all of you, but if not… 🤷🏼‍♀️I guess I’m just not a good enough explainerer. Now go write, and plan, and brainstorm, and be productive! Thanks for reading! 
            <br>-Megan 🖊️ 🎶 💣😇</p>`
    },
    {
        title: 'Loving Your Bad Writing',
        summary: `<p><em><b>By Justin Everling</b></em></p><p>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Almost every author in the world struggles with feelings of self-doubt, including myself. There’s some days where we feel that our writing is amazing. And then there’s those days where we think it’s terrible, that we should just give up.
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sometimes we write poorly—and that’s okay, because what matters is getting those words out. They might not be what you envisioned, and they might be an awful mess that needs a bunch of work, but you can love them anyway. Instead of dwelling on how clunky your writing sounds, imagine how it will be when you revise it. Think about how you could make it better. How you could improve it. Don’t go comparing yourself to other writers and feeling that your work will never be as good as theirs, because it is entirely possible that your greatest expectations will be surpassed.
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Writing is a long process. More often than not, we need to just get those words on the computer screen, page, or any other outlet. And it isn’t unusual for your words to come out wrong. It’s easy to get annoyed at yourself. You don’t need to love your bad writing, just the vision of what it can become. Think of how you plan to fix and rewrite it. Revel in the future your story could have when it lands on a bookstore shelf. Remember: if your writing is bad now, it can be great later.
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Another thing I’ve noticed is that sometimes, when you are really struggling on a scene or particular word phrasing, you may feel that your writing is terrible. But then, when you go back and read it the next day, you find that it wasn’t quite as bad as you thought it was.
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The temptation when you are struggling with bad writing is to just quit. Pause for a day. But it is far better to simply keep on persevering. And you might be surprised with the outcome. Even if the first draft ends up far less than your desire for it, you can still rewrite. Remember—you don’t have to love bad writing itself. But you can love it if you think of the end product.
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Most importantly, never give up. It’s all too easy to get so annoyed at your bad writing that you want to delete it all, or stop writing altogether. Keep on pouring those words out of your heart. They may be awkward or downright ridiculous, but you are writing, and there will be plenty of time for improvement later.
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;When you are struggling with doubt, hating what you write, remember this: God Himself has put a story in your heart, a small light in the darkness, an idea that can change the world. And no one else in the entire universe can write it the way it should be written—except you.
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Keep on loving your bad writing, because you have a job to do. A mission to accomplish.
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A story to tell.
        </p>`
    },
    {
        title: 'Virtue',
        summary: `<p><em><b>By Jadon Smith</b></em></p><p>Virtue. Such a beautiful word, no? The world has neglected the priority of pursuing virtues, and thus few people realize how vastly they affect everyday life. Your everyday life. This article was inspired by another article by my fellow Counterculture for Christ writer, Megan Kissling. In it, she mentioned how patience is a virtue needed in writing. I have reflected on virtues for hours, but never before had I thought of them in the context of writing. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;“But why not?” I thought, “Why not explore how virtues apply to writing?” And thus inspiration struck–the reason I write to you, now. I wish to impart my introspections on a virtue fundamental to writing beautifully, so that you may shine bright for Christ.
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Our virtue of discussion is known as epistemological humility (or intellectual humility). An intimidating term, for sure, but allow me to break it down. Epistemology is the study of how we, as humans, gain knowledge and discover Truth. The best way to describe humility is the opposite of pride, which believes it is the center of the world, thinks it has everything figured out, and lives as if it is more important than others.  Therefore, epistemological humility is the attitude of, “Okay,  I do not know everything, and because I do not know everything, I am willing to learn and consider perspectives I do not like.” It is being open-minded in growing your view of the world. 
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;How does that apply to writing? Let me give you a scenario: 
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;There are two writers of the same skill.. One writer believes he writes the absolute best books of all time. He thinks that there is no room for improvement or critique, and never learns about how to write well. “Eh, I’ll figure it out myself,” He says. 
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The second writer believes his books aren’t the greatest. They need to be worked on more. Maybe he doesn’t know how they need to be improved, but he seeks out help from people who do know how. He lets them suggest improvements, he lets them critique his work, and he searches for ways to improve his writing. “I don’t know everything, and I’m not the greatest writer, but I’m willing to learn how to better myself.”
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;What differentiates these two writers? Epistemological humility. The first writer refused to learn how to improve, and because of that, he never saw where he could improve. He created his own little echo chamber. The second writer, however, did not build up this wall. He accepted that he still had much to learn and thus sought out help from friends and mentors. He studied how to be better at writing and improved where he could.
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This is the benefit of epistemological humility in writing. Accepting your imperfections and beginning your journey to improve and grow is a necessity for any and all writers. It is the first big step from casual writing to serious writing. And anyone can start this trek. It may be a bit scary–you will probably trip and fall a few times–but I can assure you, it is worth it. 
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The idea of improving my writing didn’t occur to me until two years ago. Back then, I wrote for fun, but a part of me screamed, “I want to be a writer!” Ironically, It wasn’t until I wrote a short story, titled Somnolent Truth, that I was awakened to my inadequate writing prowess. I sent the story to my best friend, and she asked if she could help edit some of it. I thought, why not?
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It is worth noting that she was quite literally going to go to college for editing. Within a few hours, she had hundreds of comments on the document, and by the end, there were so many that my phone couldn’t pull up the document without slowing down to a snail’s pace. For lack of better words, that was an experience. I found out dozens of tips I never knew about and problems I didn’t know I had. My grammar was that of a cat on catnip–all over the place before falling asleep for half a day–and my dialogue… Let’s just leave it at “I didn’t know a whole lot about writing dialogue back then.”
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Was all the edits a bit humbling? Most certainly. Was I a bit insecure about it? Also most certainly. But did I learn? Most certainly of all. That singular experience propelled me further than I would have ever imagined, and I believe it was my first step towards serious writing.
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;We all have to start somewhere. Sometimes our talents get us farther than others, but eventually we all come across this path. This path of epistemological humility leads to improvement. The path winds up and down cliffs and valleys, around and through mountains and forests. It is the journey of a lifetime. 
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Imagine a crisp, cold day in the mountains. You are snuggled up in a warm coat and your backpack is brimming with supplies. Snow covers the landscape to your left, but to your right is a forest of looming conifer trees. A path carves deep into it and up a slope. Are you willing to brave the chill and terrain and come out better than you were before?
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Are you ready to write beautifully?</p>
   `},
    {
        title: 'Are you writing wrong?',
        summary: `<p><em><b>By Emma Dooley</b></em></p><p>I always heard that people write in specific ways. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You plot or you pants. Plotting being planning your story out. Step by step. Chapter by chapter. Pantsing following the saying of 'fly by the seat of your pants' or letting the story lead you from the beginning to the end with guideline to follow. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;For years I didn't hear of anything in between. But I didn’t do either of those. I found studying different writing techniques to be wildly fascinating and yet, incredibly frustrating. It left me feeling like I wasn’t good enough. Like every word I wrote was a waste of my time and the time of anyone who ever tried reading it. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I thought I could never be a ‘real writer’ if I didn’t start following the rules. I tried. I failed. I kept trying and kept failing. There was starting to be a part of me that wanted to give up. 
        I truly didn’t believe I could ever do it. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Somedays, the only thing that got me to put my pen to the page was that I knew God called me to write for a reason. His reason was never to make me feel like an outcast in the writing world. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I let go of trying to fit into the categories of plotter and pantser and I just wrote my way. But I still wanted to know what “my way” was. So, while I accepted that my way may be just that, I never stopped looking at the writing styles of others. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Learning to let go of my need to follow a certain standard, one I had put on myself, wasn’t easy. But it was worth it. It gave me the freedom to explore writing styles without constant pressure. It let me learn from everyone instead of just the ones who write like me. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It wasn’t until a couple years ago that I heard about “writing from the end”. I thought maybe that was the category I fell in. As I looked more into writing from the end, I found that it was very much how it sounds. You write the end of your book, and then the climax, and slowly work your way to the start. And that certainly wasn’t my style. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;But it made me realize what my style is. I like to call it inside out writing or puzzle writing. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I write scenes. Maybe I write the climax, then jump to the beginning. I move to the end, then come to the middle. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It's not pure chaos in one document or scrambled up chicken scratch in some notebook. I keep it organized. Each scene gets its own labeled document or a fresh page in a notebook with a colorful label across the top. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Does it feel a little crazy? Yes. Is it out of control? Maybe. But do I enjoy it? Absolutely. When I have enough scenes written out, I get to sort them all out. Like putting together puzzle pieces. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Is this your writing style? Probably not. But my goal isn't to find your style, but to tell you you’re not alone. Writing isn’t black and white. It's not one way or another. Writing is whatever you make it. It doesn’t matter what your style is, you aren’t writing wrong. You’re just writing in the way that works for you. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Don’t try to fit in someone else’s box when yours is perfect for you. Enjoy the process.</p>`
    },
    {
        title: 'Writing Process Overview!',
        summary: `<p><em><b>By Megan Kissling</b></em></p><p>Many times during my first two years of seriously writing I felt lost, utterly confused and completely idiotic whenever I sat down with my notebook and pen to start writing. I struggled to wrap my mind around forming workable plots, crafting good, relatable characters and even just the writing itself, like, my first partial draft (which I still have😖as a reminder of what NOT to do) was written half in first person and half in third person…don’t even ask how that happened. I have no answer for you other than I’ve learned a lot since then. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;But whenever I sat down to work on my writing I ended up stopping after just a few minutes in, fully stressed out just from thinking about how much I still had left and feeling ridiculous for the only three or four hundred words I was able to hand write every day. On top of that fact, my parents and family didn’t know I’d started writing and I never was able to take the time to research and learn how to properly write. I never thought about it at the time but a major part of my problem, aside from the obvious lack of narrative skill, my lack of writing skill and access to writing resources in general, and my families exclusion from my attempts, was that I had no outline or guide to help me keep track of everything I created and to help me realize that completing a chapter with a clear end goal in mind was actually getting me somewhere. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Thinking about how much I had to do was…quite frankly, overwhelming. Like, there’s so much that goes into a story, how do you know where to even start?? Obviously I did not have any clue where to start as it took another year and a half before I finally managed to determine the difference between narratives and actually finish a full length novel draft and then publish it.🫣 So, that is what I’m going to be providing here, an outline to help you do better at writing then I did when I first started. There is a lot to cover so for now I’ll just do a brief overview, then over the next few weeks I’ll go over each piece in depth. I hope you’re able to gather something from this, whether it just be encouragement that no matter how young you are it is possible to do great things. Philippians 4:13 “I can do all things through Christ who strengthens me.” Happy reading!</p>
                <h3>Inspiration/Idea</h3>
                <p>Every good book starts with a little bit of inspiration, an idea. Where a lot of new writers go wrong is thinking that you have to have a J. R. R. Tolkien level plot, complete with an entire language that you made up yourself. This, while absolutely astonishing if you’re just naturally the next J. R. R. Tolkien Junior and can come up with a complex storyworld without having a brain overload, is not true. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No story just comes to an author, themes, character arcs, plots and conflicts all wrapped up neatly in a little package and tied off with a green shiny ribbon. No, oftentimes it’s just a wisp of an idea, floating into your mind after listening to a song, watching a movie, or even just staring out the car window and observing how blue the sky is in that particular moment, and yes, I have done that before. Maybe it’s just a sentence, or a word. It sparks your interest, sets off explosions of excitement and slowly builds into something more. For instance, I was watching Ben-Hur with my family the other day and all of a sudden, during the most riveting, exciting part of the entire movie (the chariot race of course😜) inspiration for a gladiator type book struck. Actually to be specific I think it was right when one of the charioteers tried to run Ben-hur into the wall, my mind went “Oooh, what if I had a character do that but actually succeed in running the other person into the wall.” 🤦‍♀️don’t mind my slightly ruthless brain, it’s fine, I'm fine, I’m just an author not a serial killer. Alright, moving on, basically the point of what I just said was that your idea doesn’t have to be cultivated halfway to China, a simple idea can turn into an amazing story. Your story! </p>
                <h3>Preparation</h3>
                <p>Preparation is the next step to completing a novel. A lot of people are intimidated by the word because generally prepping stuff isn’t that fun, and takes forever, well, at least most of forever. But in reality, preparation is probably going to be one of the easiest parts of the entire writing process, so easy that there are some people who don’t even do it and just keep everything in their heads…kudos to you if your brain can handle all that and not forget anything, <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I personally have to make a general outline of my story idea, characters, and storyworld or I’d start having some major problems. Preparation is basically just a lot of outlining: character outlines, overall story outlines, chapter outlines, story world outlines, making sure that I don’t go insane with how much stuff there is to keep track of outlines…you could make up an outline for literally anything. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I know, that seems like a lot and you’re probably starting to feel overwhelmed. Don’t. It looks like a lot, it sounds like a lot, some of it may even be a lot, especially if you’re a perfectionist like me, but it also can be really simple, many of these outlines don’t even take that long, maybe fifteen minutes, and a few of them, depending on your story, aren’t even necessary, actually, technically none of them are necessary but for us people who have forgetful brains and need something to help us keep track of our billions of ideas, outlining is one of the most helpful things in the whole history of writing. Don’t stress about it! When I do another post, going into more detail about preparation, I’ll hopefully have some free, downloadable outline sheets that I use regularly in my own writing to help you along a bit!</p>
                <h3>Drafting</h3>
                <p>Drafting is the next step to finishing a book. It's the part that everyone loves, as long as they have inspiration to write, and the part everyone dreads when writers block hits and all you want is to have your precious novel published and a physical copy with a beautiful cover in your hands. It's the easiest, yet hardest part of the whole process, and will produce the major portion of tears, stress, happiness, and excitement. Basically, it's the best. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Drafting is where you write down your entire novel, without making any edits or revisions whatsoever, and don’t stop until every last word of that story you’ve been longing to tell is in existence. This will take a lot of perseverance, consistency, effort and patience. Yes, you read it right, never thought you’d learn a virtue or two while writing, did you? I certainly didn’t. I learned it real fast though, as soon as a month passed of my first writing course and I still had nothing on paper because I’d not waited for my teacher's guidance and my chapters were absolutely unworthy of being read, so I ditched them. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I strongly recommend to anyone just starting out to go watch a few YouTube videos on writing, or just find a course to sign up for cause without that, I would have been completely lost. This doesn’t mean that if you’ve never watched writing videos or read books about writing or even taken a course on writing that your book draft will be as awful as mine, but it saves so much time in revisions if you don’t just rush headlong into something and don’t have any patience to learn how it’s actually supposed to be done. </p>
                <h3>Revision/Editing</h3>
                <p>The next step is the revision and editing process, this for some people can be as difficult or more than drafting was. The main reason for that is because you’ve just spent hours upon hours, days upon days, weeks upon weeks, I could keep going up but it’s starting to get old so hopefully you get the point- working on your book, your “child” as many of us authors call it and in revisions your “child” is going to change. A lot. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This isn’t true all the time, but more often than not, that’s just how it goes, maybe it’s because to fix a plot hole you have to add an entirely new character, somehow incorporate that new person into your MC's life and the events they go through. Maybe it’s taking out a scene because it just sounds like garbage, then when you start the rewrite the entire chapter then needs to be ditched because you had a genius new idea to add. The list continues. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;People shy away from this because they spent all that time pouring their very souls into that “child” and they don’t want them to change. At all. Even if it’s for the better. It actually is genuinely sad and emotional for them to change it. I get it. It’s hard. I did NOT want to do it either, like, I’d spent five months writing the draft, why in the world would I change it???? Because no matter how good of a writer you are, every first draft needs to be revised, edited and changed. Not just to be changed, but to make it better. My book is better for it. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Although, I’ve still got a ways to go before it’ll be anywhere near as good as some of my favorite authors. Your book will be better for it too! (Note: Editing and Revision are two different processes, Revision is usually the first set of changes you make to your book, the major ones where you fix plot holes, take out and add scenes. Editing is generally where you check for grammar and do line edits, smaller things like that.)</p>
                <h3>Publication/Marketing</h3>
                <p>This is what you’ve been waiting for. Dreaming of. Your book. Published. A physical copy in your hand. Your name on the cover. You’ve spent countless hours toiling over this masterpiece, persevering with undeterrable determination. And it’s finally done. First off, when you reach this point in your writing, you’d better celebrate. Buy some ice cream, cookies, or chocolate. Splurge a little. Pat yourself on the back and scream about it in all caps over chat to your best friend. …don’t look at me like that, trust me, it’s normal, you’ll understand how…freeing it is to go do that, especially when they yell back. And then email me so I can congratulate you on that achievement…in all caps.🤭 but seriously, that’s a big accomplishment. You should be proud. Because. You. Did. It. 🥳🥳
                <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Now that you’ve done all that celebrating it’s time to get serious. You may have finished your book, and gotten it published, but your work's not over. Thousands of books are published regularly, it won’t be long before your book is buried beneath how many others. It’s your job to keep that from happening. How, you may ask? Marketing. Build a blog, an Instagram account, a YouTube channel, even a simple newsletter. Make an effort to go to writers conferences, meet other authors, and spread the word about your book. Don’t be shy. To get your book out there, you have to get out there. 
                <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;So there you are! A brief overview of the writing process! How do you feel? Excited? Slightly hesitant? Hopefully it's the former. I”ll be diving deeper into each step soon so stick around to get more info! Thanks for reading!
                <br><br>-Megan 🖊️ 🎶 💣😇
                </p>`
    }
];

// expose articles so pages can access them
window.articles = articles;

// Set the latest article (assuming the first one is the most recent)
window.latestArticle = articles[0];

// Function to extract author from summary
window.getAuthor = function(summary) {
    const match = summary.match(/<b>By ([^<]+)<\/b>/);
    return match ? match[1] : 'Unknown';
};

// Turn a plain-text or HTML summary into safe HTML with paragraph tags.
function _toHtmlSummary(html) {
    if (!html) return '';
    const str = String(html);
    const trimmed = str.trim();
    // If it already looks like HTML, return as-is (trusting the source a bit).
    if (trimmed.startsWith('<')) return str;

    // Escape HTML special characters then wrap paragraphs separated by blank lines.
    function escapeHtml(s) {
        return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    }

    const parts = str.split(/\n\s*\n+/).map(p => p.trim()).filter(Boolean);
    return parts.map(p => `<p>${escapeHtml(p).replace(/\n/g, '<br>')}</p>`).join('\n');
}



// Render all articles into a container (useful for articles.html)
window.renderAllarticles = function(selector) {
    const container = document.querySelector(selector);
    if (!container) return;
    container.innerHTML = '';

    const heading = document.createElement('h1');
    heading.textContent = 'Blog Articles:';
    container.appendChild(heading);

    // Group articles by author
    const authorArticles = {};
    articles.forEach(article => {
        const author = window.getAuthor(article.summary);
        if (!authorArticles[author]) authorArticles[author] = [];
        authorArticles[author].push(article);
    });

    // Sort authors by last name
    const sortedAuthors = Object.keys(authorArticles).sort((a, b) => {
        const lastA = a.split(' ').pop();
        const lastB = b.split(' ').pop();
        return lastA.localeCompare(lastB);
    });

    // Articles by author, sorted
    sortedAuthors.forEach(author => {
        const banner = document.createElement('h2');
        banner.textContent = `Articles by ${author}`;
        banner.style.textAlign = 'center';
        container.appendChild(banner);

        authorArticles[author].forEach(item => {
            const el = document.createElement('article');
            el.id = item.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-$/, '');
            el.innerHTML = `<h3>${item.title}</h3>` + _toHtmlSummary(item.summary);
            container.appendChild(el);
        });
    });
};
